---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helm-repo
spec:
  template:
    metadata:
      labels:
        app: helm-repo
      name: helm-repo
    spec:
      containers:
      - image: hanyifeng/helm-repo
        imagePullPolicy: Always
        name: helm-repo
        ports:
          - containerPort: 80
            name: helmserveport
            protocol: TCP
        env:
          - name: KUBERNETES
            value: "yes"
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "100Mi"
            cpu: "100m"
        livenessProbe:
          failureThreshold: 8
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: helm-repo
spec:
  selector:
    app: helm-repo
  type: NodePort
  ports:
  - name: helmserveport
    port: 80
    protocol: TCP
    targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: helm-repo
  name: helm-repo
spec:
  rules:
  - host: charts.example.com
    http:
      paths:
      - backend:
          serviceName: helm-repo
          servicePort: 80
        path: /

